version: "3.9"  # optional since v1.27.0
services:

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest_api
    ports:
      - "8001:5432"

  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000"