version: "3.9"  # optional since v1.27.0
services:

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432

  api:
    container_name: nest_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
       DB_HOST: database
       DB_PORT: 5432